In [1]:
import numpy as np

In [2]:
my_matrix = [[5,10],[15,20]]

In [4]:
my_matrix[0]

[5, 10]

In [5]:
my_matrix[0][1]

10

In [7]:
# row * column

In [12]:
numpy_matrix = np.array([[5,10],[15,20]])

In [13]:
numpy_matrix

array([[ 5, 10],
       [15, 20]])

In [14]:
numpy_matrix[1][0]

np.int64(15)

In [15]:
numpy_matrix.sum()

np.int64(50)

In [19]:
np.ones((4,2)) #column , row

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
np.ones((4))

array([1., 1., 1., 1.])

In [21]:
#matrix arithmetic 

In [23]:
first_array = np.array([[10,20],[30,40]])
second_array = np.array([[5,15],[25,35]])

In [24]:
first_array + second_array

array([[15, 35],
       [55, 75]])

In [25]:
first_array

array([[10, 20],
       [30, 40]])

In [26]:
second_array

array([[ 5, 15],
       [25, 35]])

In [27]:
third_array = np.array([[50,60]])

In [28]:
first_array + third_array

array([[ 60,  80],
       [ 80, 100]])

In [41]:
fourth_array = np.array([[10,20,30,40,50]])

In [42]:
first_array+ fourth_array

ValueError: operands could not be broadcast together with shapes (2,2) (1,5) 

In [31]:
first_array / 2

array([[ 5., 10.],
       [15., 20.]])

In [32]:
first_array / 4

array([[ 2.5,  5. ],
       [ 7.5, 10. ]])

In [33]:
third_array.shape

(1, 2)

In [34]:
#matrix multiplication

In [35]:
first_array * second_array

array([[  50,  300],
       [ 750, 1400]])

In [36]:
# dot product

In [39]:
first_matrix = np.array([[10,20,30]])

In [40]:
first_matrix.shape

(1, 3)

In [43]:
second_matrix = np.array([[2,3],[2,3],[2,3]])

In [44]:
second_matrix.shape

(3, 2)

In [45]:
result_matrix = first_matrix.dot(second_matrix)

In [46]:
result_matrix

array([[120, 180]])

In [47]:
result_matrix.shape

(1, 2)